### ISSUE TITLE
Suggestion: Enhance Motor Power User Experience

### ISSUE THREAD

**Issue by Koloss0** [cyberneel/InfiniTime#4]
**Suggestion:**
Currently, when I change the motor power, I can't recall the felt intensity of the value, so I have to press the test button. It would be slightly more ergonomic for the user if you could combine the two buttons so that changing the setting also triggers the test immediately.

Not part of the bounty, btw.

**Comment by thiswillbeyourgithub** [comment]
I think this was done and can be closed now

**Comment by liamcharger** [comment]
Just implemented in the latest commit.
